### ISSUE TITLE
Mongeez fails with: can't authenticate twice on the same database

### ISSUE THREAD

**Issue by d0x** [mongeez/mongeez#47]
When using this code snipped:

```
    @Bean
    public Mongeez mongeez()
    {
        log.debug("Configuring Mongeez");
        Mongeez mongeez = new Mongeez();
        mongeez.setFile(new ClassPathResource("/config/mongeez/master.xml"));
        mongeez.setMongo(mongo);
        mongeez.setAuth(new MongoAuth(mongoProperties.getUsername(), new String(mongoProperties.getPassword())));
        mongeez.setDbName(mongoProperties.getDatabase());
        mongeez.process();
        return mongeez;
    }
```

I get this exception:

```
Caused by: java.lang.IllegalStateException: can't authenticate twice on the same database
    at com.mongodb.DB.authenticateCommandHelper(DB.java:760)
    at com.mongodb.DB.authenticate(DB.java:721)
    at org.mongeez.dao.MongeezDao.<init>(MongeezDao.java:41)
    at org.mongeez.ChangeSetExecutor.<init>(ChangeSetExecutor.java:36)
    at org.mongeez.Mongeez.process(Mongeez.java:40)
```

I am not sure whether there is a "collision" with my spring managed `MongoClient`. Have you ever experienced this issue?

I'm trying to adjust the jhipster.github.io scafold to my needs.

Versions:
- Mongo 2.4.9
- Mongeez 0.9.4
- Mongo Java Driver 2.12.3
- Spring Data Mongo 1.5.4

Best Regards,
Christian.

**Comment by avishrimali** [comment]
I am also facing the same issue, is there any solution for this?
