### ISSUE TITLE
Mongeeze failed with replicaset and mongoProperties.setUri used 

### ISSUE THREAD

**Issue by UltimateFighter** [mongeez/mongeez#60]
Hello,

i have a mongodb with replicaset and ssl enabled.

i use mongoProperties.setUri on this configuration.

!currently i must do this (see: https://github.com/spring-projects/spring-boot/issues/4051)

is use:

- javax.net.ssl.trustStore
- javax.net.ssl.trustStorePassword
- uri: mongodb://[#USER]:[#PASS]@[#MY-REPLICASET-HOST-1]:27017,[#MY-REPLICASET-HOST-2]:27017,[#MY-REPLICASET-HOST-3]:27017/[#DATABASE]?ssl=true

Here is the Exception if i start my application :

> 09:02:45.280 [localhost-startStop-1] INFO  org.mongodb.driver.cluster - No server chosen by WritableServerSelector from cluster description ClusterDescription{type=UNKNOWN, connectionMode=MULTIPLE, all=[ServerDescription{address=[#MY-REPLICASET-HOST-1]:27017, type=UNKNOWN, state=CONNECTING}, ServerDescription{address=[#MY-REPLICASET-HOST-2]:27017, type=UNKNOWN, state=CONNECTING}, ServerDescription{address=[#MY-REPLICASET-HOST-3]:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
09:02:45.289 [cluster-ClusterId{value='[#CLUSTER-ID]', description='null'}-[#MY-REPLICASET-HOST-2]:27017] INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server [#MY-REPLICASET-HOST-2]:27017
com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.connection.SocketStream.read(SocketStream.java:88) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:491) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:221) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.CommandHelper.receiveReply(CommandHelper.java:134) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:121) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:83) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:43) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) ~[mongo-java-driver-3.2.2.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]

**Comment by leandrolimasi** [comment]
+1 same error here
